version: '3.8'

services:
  app:
    image: mon-utilisateur/mon-application  # Remplacez par votre nom d'utilisateur Docker Hub et le nom de l'image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production